server:
  port: 8098

spring:
  application:
    name: support-service
  cloud:
    config:
      enabled: true
      uri: http://config-server:8888
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10
  config:
    import: optional:configserver:http://config-server:8888

logging:
  level:
    com.civileng.marketplace.support: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
